In [7]:
import tensorflow as tf
import numpy as np
import pprint as pp
tf.__version__

'1.14.0'

## 1차원

In [8]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)       # rank(차원)
print(t.shape)      # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2차원

In [9]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.,], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)           # rank
print(t.shape)          # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [18]:
sess = tf.InteractiveSession()
t = tf.constant([1, 2, 3, 4])           # rank = 1
tf.shape(t).eval()

array([4])

In [19]:
t = tf.constant([[1, 2],                # rank = 2
                 [3, 4]])
tf.shape(t).eval()                      # shape = (행의 개수, 열의 개수)

array([2, 2])

In [21]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],                     # rank = 4
                    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 23]]]])
tf.shape(t).eval()                                                                  # shape = (제일 큰 단위 하나, 행의 개수, 열의 개수,rank)

array([1, 2, 3, 4])

In [29]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])

print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)

tf.matmul(matrix1, matrix2).eval()              # shape = (2, 1)

## (matrix1 * matrix2).eval()      ==>     안됨 이렇게하면 because broadcasting 기능 때문

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

## Broadcasting

#### 차원에 상관없이 늘려서 맞춰서 계산하는 기법

In [33]:
# 같은 shape
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])

(matrix1 + matrix2).eval()

array([[5., 5.]], dtype=float32)

In [30]:
# 다른 shape

matri1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)

(matri1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

In [31]:
matri1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])

(matri1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [32]:

matri1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])

(matri1 + matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

## Reduce mean

#### 평균을 구하는데 값을 줄여서 구하기

In [35]:
tf.reduce_mean([1, 2], axis=0).eval()           # 원래 평균은 1.5

1

In [36]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval()                        

2.5

In [37]:
tf.reduce_mean(x, axis=0).eval()                # axis = 1 or -1(제일 안쪽 축 기준)이면 행 / 0이면 열 기준

array([2., 3.], dtype=float32)

In [38]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [39]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

## Reduce sum

#### 합을 구하는데 값을 줄여서 구하기

In [40]:
tf.reduce_sum(x).eval()

10.0

In [41]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [42]:
tf.reduce_sum(x,axis=-1).eval()

array([3., 7.], dtype=float32)

In [43]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax

#### 축을 기준으로 가장 큰 값의 인덱스를 반환

In [47]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [49]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [50]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape

#### 형태를 바꾸기

In [52]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               
              [[6, 7, 8],
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [53]:
tf.reshape(t, shape=[-1, 3]).eval()             # shape의 마지막 값인 rank는 그대로 유지하는 경우가 많다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [55]:
tf.squeeze([[0], [1], [2]]).eval()              # 차원을 줄이기

array([0, 1, 2])

In [56]:
tf.expand_dims([0, 1, 2], 1).eval()             # 차원을 늘이기 => 1차원 추가

array([[0],
       [1],
       [2]])

## One Hot

In [59]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [60]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## Casting

#### 주어진 텐서를 원하는 자료형으로 바꿀 수 있다

In [62]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [63]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()         # accuracy 계산할 때 용이

array([1, 0, 1, 0])

## Stack

#### 축에 따라 텐서들을 쌓는 기능

In [65]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones like & Zeros like

#### 형태는 같지만 값이 1 혹은 0으로 채워진 텐서를 만들 때

In [70]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [71]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

#### 짝지어서 묶어서 반환한다

In [73]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [74]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
