In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [3]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. 엄청 작은 수의 learning rate 필요
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  188104.06 
Prediction:
 [-238.50362 -274.49374 -276.9481  -299.80432 -207.67018]
10 Cost:  12.254836 
Prediction:
 [145.16461 186.62366 177.41083 194.97935 144.04202]
20 Cost:  10.480497 
Prediction:
 [146.33768 188.01048 178.78935 196.47874 145.0956 ]
30 Cost:  10.4283085 
Prediction:
 [146.35341 188.00636 178.7973  196.4856  145.08821]
40 Cost:  10.3764105 
Prediction:
 [146.36562 187.99806 178.8011  196.48795 145.07765]
50 Cost:  10.324799 
Prediction:
 [146.37779 187.98979 178.80489 196.49028 145.06712]
60 Cost:  10.273423 
Prediction:
 [146.38991 187.98149 178.80867 196.4926  145.0566 ]
70 Cost:  10.222368 
Prediction:
 [146.40201 187.97325 178.81241 196.4949  145.04611]
80 Cost:  10.171602 
Prediction:
 [146.41405 187.96501 178.81615 196.4972  145.03564]
90 Cost:  10.1210575 
Prediction:
 [146.4261  187.95682 178.81992 196.49951 145.02524]
100 Cost:  10.070806 
Prediction:
 [146.4381  187.94862 178.82362 196.50179 145.01483]
110 Cost:  10.020842 
Prediction:
 [146.45006 

1330 Cost:  5.5610933 
Prediction:
 [147.6947  187.0922  179.21503 196.73537 143.93279]
1340 Cost:  5.535251 
Prediction:
 [147.70334 187.08632 179.21773 196.73692 143.92542]
1350 Cost:  5.509568 
Prediction:
 [147.71193 187.08044 179.22041 196.73846 143.91806]
1360 Cost:  5.484039 
Prediction:
 [147.72052 187.07463 179.2231  196.74    143.91075]
1370 Cost:  5.4586353 
Prediction:
 [147.72908 187.06882 179.22577 196.74155 143.90344]
1380 Cost:  5.433366 
Prediction:
 [147.7376  187.06299 179.22842 196.74307 143.89613]
1390 Cost:  5.4082355 
Prediction:
 [147.74611 187.0572  179.2311  196.74461 143.88887]
1400 Cost:  5.3832407 
Prediction:
 [147.75458 187.0514  179.23373 196.7461  143.88162]
1410 Cost:  5.3583603 
Prediction:
 [147.76306 187.04565 179.23639 196.74763 143.8744 ]
1420 Cost:  5.33365 
Prediction:
 [147.77148 187.0399  179.23901 196.74915 143.86719]
1430 Cost:  5.3090353 
Prediction:
 [147.77992 187.03418 179.24165 196.75066 143.86002]
1440 Cost:  5.28456 
Prediction:
 [147

In [4]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  64038.773 
Prediction:
 [[-77.715164]
 [-81.993576]
 [-86.61784 ]
 [-94.515495]
 [-59.630653]]
10 Cost:  11.3867855 
Prediction:
 [[146.13858]
 [187.03793]
 [178.47598]
 [194.16362]
 [145.56786]]
20 Cost:  10.74322 
Prediction:
 [[146.82854]
 [187.84328]
 [179.28195]
 [195.03987]
 [146.17737]]
30 Cost:  10.686081 
Prediction:
 [[146.84322]
 [187.83705]
 [179.28824]
 [195.0453 ]
 [146.16786]]
40 Cost:  10.629342 
Prediction:
 [[146.85582]
 [187.82843]
 [179.2921 ]
 [195.04808]
 [146.15654]]
50 Cost:  10.572829 
Prediction:
 [[146.86838]
 [187.8198 ]
 [179.29594]
 [195.05087]
 [146.14522]]
60 Cost:  10.516613 
Prediction:
 [[146.88095]
 [187.81122]
 [179.2998 ]
 [195.05365]
 [146.13396]]
70 Cost:  10.460779 
Prediction:
 [[146.89343]
 [187.80264]
 [179.30362]
 [195.05641]
 [146.12271]]
80 Cost:  10.405182 
Prediction:
 [[146.90591]
 [187.79411]
 [179.30746]
 [195.05919]
 [146.1115 ]]
90 Cost:  10.349903 
Prediction:
 [[146.91835]
 [187.78558]
 [179.31126]
 [195.06194]
 [146.1003

940 Cost:  6.5952635 
Prediction:
 [[147.86124]
 [187.13925]
 [179.6002 ]
 [195.27058]
 [145.25249]]
950 Cost:  6.560582 
Prediction:
 [[147.87108]
 [187.13249]
 [179.60321]
 [195.27277]
 [145.24362]]
960 Cost:  6.52608 
Prediction:
 [[147.8809 ]
 [187.12575]
 [179.60622]
 [195.27492]
 [145.23479]]
970 Cost:  6.491788 
Prediction:
 [[147.89069]
 [187.11903]
 [179.6092 ]
 [195.2771 ]
 [145.22597]]
980 Cost:  6.4576735 
Prediction:
 [[147.90047]
 [187.11235]
 [179.61221]
 [195.27927]
 [145.2172 ]]
990 Cost:  6.42372 
Prediction:
 [[147.91022]
 [187.10565]
 [179.6152 ]
 [195.2814 ]
 [145.20844]]
1000 Cost:  6.389972 
Prediction:
 [[147.91994]
 [187.09901]
 [179.61818]
 [195.28357]
 [145.19969]]
1010 Cost:  6.356414 
Prediction:
 [[147.92963]
 [187.09236]
 [179.62117]
 [195.28572]
 [145.191  ]]
1020 Cost:  6.323007 
Prediction:
 [[147.93929]
 [187.08572]
 [179.6241 ]
 [195.28784]
 [145.18228]]
1030 Cost:  6.2897897 
Prediction:
 [[147.94893]
 [187.07912]
 [179.62706]
 [195.28998]
 [145.173