# Pytorch tutorial 1

In [1]:
from __future__ import print_function
import torch

## Tensor

In [2]:
# Tensor: numpy의 ndarray와 비슷하다
x = torch.empty(5, 3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.1112e-38],
        [9.5511e-39, 1.0102e-38, 7.0715e-39],
        [9.0919e-39, 9.6429e-39, 9.2755e-39],
        [6.9796e-39, 8.9082e-39, 1.0102e-38],
        [1.0102e-38, 8.4490e-39, 1.1112e-38]])


In [3]:
# 초기화된 값(random)
x = torch.rand(5, 3)
print(x)

tensor([[0.8890, 0.2557, 0.4287],
        [0.1030, 0.0284, 0.6248],
        [0.6609, 0.4294, 0.5663],
        [0.7309, 0.9874, 0.7643],
        [0.8545, 0.0252, 0.8389]])


In [5]:
# 0으로 초기화
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [6]:
# 직접 값 입력하기
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)            # new_* 은 크기 입력을 받는다
print(x)

x = torch.rand_like(x, dtype=torch.float)           # type overwrite도 가능. 기존의 1이 입력된 x의 값에 임의의 값으로 덮어쓴다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.3795, 0.8410, 0.5389],
        [0.4778, 0.6819, 0.5157],
        [0.6277, 0.0976, 0.4907],
        [0.6031, 0.3247, 0.1956],
        [0.0521, 0.5252, 0.1928]])


In [9]:
# size 역시 같다. torch.size의 경우 tuple 자료형처럼 적용된다.
print(x.size())

torch.Size([5, 3])


## Operation, 연산

In [10]:
y = torch.rand(5, 3)
print(x.size(), y.size()) # 사이즈가 같아야 연산 가능

# 더하기의 두 가지 방법
# 1.
print(x + y)

# 2.
print(torch.add(x, y))

torch.Size([5, 3]) torch.Size([5, 3])
tensor([[0.7821, 1.2967, 1.3793],
        [0.5026, 1.2016, 1.2457],
        [1.6222, 0.5588, 1.3642],
        [1.2820, 1.1817, 0.2399],
        [0.2371, 1.1526, 0.7259]])
tensor([[0.7821, 1.2967, 1.3793],
        [0.5026, 1.2016, 1.2457],
        [1.6222, 0.5588, 1.3642],
        [1.2820, 1.1817, 0.2399],
        [0.2371, 1.1526, 0.7259]])


In [11]:
# 더한 값을 특정 변수애 넣기
res = torch.empty(5, 3)         # 넣을 변수의 사이즈도 맞추어 주어야 한다
torch.add(x, y, out=res)
print(res)

tensor([[0.7821, 1.2967, 1.3793],
        [0.5026, 1.2016, 1.2457],
        [1.6222, 0.5588, 1.3642],
        [1.2820, 1.1817, 0.2399],
        [0.2371, 1.1526, 0.7259]])


In [15]:
# 변수 y에 x+y를 넣는다. y = x+y
y.add_(x)
print(y)

tensor([[1.5410, 2.9786, 2.4571],
        [1.4582, 2.5655, 2.2771],
        [2.8775, 0.7540, 2.3457],
        [2.4882, 1.8312, 0.6310],
        [0.3412, 2.2030, 1.1116]])


In [16]:
# tensor 변수의 값을 바꾸게되는 연산자들은 뒤에 '_'가 붙는다.
# for example: x.copy_(y), x.t_(y) => x를 바꿀 것이다

In [19]:
# numpy 처럼 slicing 가능
print(x[:, 1])                  # dataframe의 슬라이싱과 동일

tensor([0.8410, 0.6819, 0.0976, 0.3247, 0.5252])


In [20]:
# tensor의 사이즈 변경
x = torch.randn(4, 4)           # 4*4 = 2*8 = 16 * 1
y = x.view(16)                  # 16 * 1
z = x.view(-1, 8)               # 여기서 -1은 남은 값들로부터 추측한다. 여기서는 2 * 8이 남았으므로 2
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
# tensor의 값이 하나뿐이라면 array 형태가 아닌 하나의 값으로도 받을 수 있다.
ㅌ = torch.randn(1)
print(ㅌ)
print(ㅌ.item())

tensor([0.9122])
0.9121751189231873


## Numpy Bridge

In [22]:
# torch의 tensor와 numpy의 array는 같은 메모리를 공유한다. 따라서 변환이 매우 쉽다.

In [23]:
# torch -> numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a, b)                 # a에만 더했는데, 같은 메모리를 공유하기에 b도 변함

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [27]:
# numpy => torch
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# CUDA가 가능한 경우
# 'torch.device' 객체를 사용해 GPU로 tensor를 이동시킬 수 있다.

if torch.cuda.is_available():
    print('available!_!')
    device = torch.device("cuda")           # cuda 객체 받기
    y = torch.ones_like(x, device=device)   # GPU에서 tensor 생성
    x = x.to(device)                        # tensor를 GPU로 보내서 생성
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))        # .to 모듈은 dtype도 바꿀 수 있다

else:
    not print('not available')

available!_!
tensor([[-0.1405,  0.5138,  2.3461,  2.1653],
        [ 1.8154,  1.5245,  1.0235,  1.0533],
        [ 0.7650,  2.0506,  1.9110,  2.0496],
        [ 0.0289,  2.6485,  0.8314,  0.1394]], device='cuda:0')
tensor([[-0.1405,  0.5138,  2.3461,  2.1653],
        [ 1.8154,  1.5245,  1.0235,  1.0533],
        [ 0.7650,  2.0506,  1.9110,  2.0496],
        [ 0.0289,  2.6485,  0.8314,  0.1394]], dtype=torch.float64)
