# RNN

In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pprint as pp

In [7]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

hidden_size = 2                                                 # 출력값의 차원 크기가 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())

array([[[-0.02286422, -0.01843275]]], dtype=float32)


In [10]:
## sequence를 5로 설정
tf.reset_default_graph()
sess = tf.InteractiveSession()

hidden_size = 2                                                 # 출력값의 차원 크기가 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

# one hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

x_data = np.array([[h, e, l, l, o]], dtype=np.float32)           # 시퀀스가 5(h,e,l,l,o))
print(x_data.shape)
pp.pprint(x_data)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
array([[[-0.08621567,  0.02229959],
        [-0.13066664, -0.03033137],
        [-0.11400522, -0.10875792],
        [-0.09169253, -0.16604638],
        [-0.1809616 , -0.10848189]]], dtype=float32)


In [11]:
## batch size 설정
tf.reset_default_graph()
sess = tf.InteractiveSession()

hidden_size = 2   

x_data = np.array([[h, e, l, l, o],
                    [e, o, l, l, l],
                    [l, l, e, e, l]], dtype=np.float32)                         # batch_size가 3이다

pp.pprint(x_data)

cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)

outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
array([[[-0.04989181,  0.0251299 ],
        [-0.02114385, -0.11054849],
        [-0.14788543, -0.12186845],
        [-0.2114226 , -0.15461153],
        [-0.1832151 , -0.08081879]],

       [[ 0.01318265, -0.11524928],
        [-0.06544366, -0.02285126],
        [-0.1768936 , -0.06973846],
        [-0.22775711, -0.11750108],
        [-0.2519708 , -0.16067542]],

       [[-0.1425745 , -0.04141676],
        [-0.21199252, -0.09108209],
        [-0.16238724, -0.20074753],
        [-0.11338816, -0.24849628],
        [-0.18862401, -0.22968963]]], dtype=float32)


In [12]:
# one hot encoding
h = [1, 0, 0, 0, 0]
i = [0, 1, 0, 0, 0]
e = [0, 0, 1, 0, 0]
l = [0, 0, 0, 1, 0]
o = [0, 0, 0, 0, 1]

In [14]:
## RNN model
tf.reset_default_graph()
sess = tf.InteractiveSession()

hidden_size = 5
input_dim = 5
batch_size = 1
sequence_length = 6

idx2char = ['h', 'i', 'e', 'l', 'o']
x_data = [[0, 1, 0, 2, 3, 3]]
x_one_hot = [[[1, 0, 0, 0, 0],
            [0, 1, 0, 0, 0],
            [1, 0, 0, 0, 0],
            [0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 1, 0]]]
y_data = [[1, 0, 2, 3, 3, 4]]

X = tf.placeholder(tf.float32, [None, sequence_length, input_dim])
Y = tf.placeholder(tf.int32, [None, sequence_length])

cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, X, initial_state=initial_state, dtype=tf.float32)

In [15]:
# seq_loss

y_data = tf.constant([[1, 1, 1]])

prediction = tf.constant([[[0.2, 0.7], [0.6, 0.2], [0.2, 0.9]]], dtype=tf.float32)

weights = tf.constant([[1, 1, 1]], dtype=tf.float32)

sequence_loss = tf.contrib.seq2seq.sequence_loss(logits=prediction, targets=y_data, weights=weights)

sess.run(tf.global_variables_initializer())

print("Loss: ", sequence_loss.eval())

Loss:  0.5967595
